#!/bin/sh
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
./screen -S Nautilus0 -X stuff Q
